04-03 15:22:30 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "saless" not found; SQL statement:
Insert into Utilisateur VALUES (1, "saless", "fabien", "0123456789") [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-03 15:23:39 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "saless" not found; SQL statement:
Insert into Utilisateur(idUtilisateur,nom,prenom,telephone) VALUES (1, "saless", "fabien", "0123456789") [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
04-03 15:24:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "saless" not found; SQL statement:
Insert into UTILISATEUR values (1, "saless", "fabien", "0123456789") [42122-147]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:126)
	at org.h2.command.dml.Insert.prepare(Insert.java:224)
	at org.h2.command.Parser.prepare(Parser.java:202)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1056)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:165)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1004)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:970)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
